import { Lato } from "next/font/google";
import "./globals.css";
import Nav from "@/components/Nav";

const lato = Lato({ subsets: ["latin"], weight: "400" });

export const metadata = {
  title: "Next GPT",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${lato.className} mx-auto max-w-7xl`}>
        <Nav />
        <div>{children}</div>
      </body>
    </html>
  );
}
